version: '2'
services:
    nginx-proxy:
       image: jwilder/nginx-proxy:latest
        container_name: nginx-proxy
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        ports:
            - 80:80
        restart: always

    sabnzbd:
        image: linuxserver/sabnzbd:latest
        container_name: sabnzbd
        volumes:
            - /home/plex/config/sabnzbd:/config
            - /home/plex/Downloads/complete:/downloads
            - /home/plex/Downloads/incomplete:/incomplete-downloads
        ports:
            - 8080:8080
        env_file: uidgid.env
        environment:
            - EDGE=1
            - VIRTUAL_HOST=sabnzbd.misury.tv
            - VIRTUAL_PORT=8080
        restart: always

    couchpotato:
        image: linuxserver/couchpotato:latest
        container_name: couchpotato
        volumes:
            - /home/plex/config/couchpotato:/config
            - /home/plex/Downloads/complete:/downloads
            - /home/plex/Movies:/movies
        ports:
            - 5050:5050
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=couchpotato.misury.tv
            - VIRTUAL_PORT=5050
        restart: always

    plex:
        image: plexinc/pms-docker
        container_name: plex
        volumes:
            - /home/plex/config/plex:/config
            - /home/plex/TV:/data/tvshows
            - /home/plex/Movies:/data/movies
        ports:
            - 32469:32469
            - 32400:32400
            - 32401:32401
            - 3005:3005
            - 8324:8324
            - 1900:1900/udp
            - 32410:32410/udp
            - 32412:32412/udp
            - 32413:32413/udp
            - 32414:32414/udp
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=plex.misury.tv
            - VIRTUAL_PORT=32400
        restart: always

    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        volumes:
            - /home/plex/config/sonarr:/config
            - /etc/localtime:/etc/localtime:ro
            - /home/plex/TV:/tv
            - /home/plex/Downloads/complete:/downloads
        ports:
            - 8989:8989
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=sonarr.misury.tv
            - VIRTUAL_PORT=8989
        restart: always

    plexpy:
        image: linuxserver/plexpy
        container_name: plexpy
        volumes:
            - /home/plex/config/plexpy:/config
            - /etc/localtime:/etc/localtime:ro
            - /home/plex/config/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
        ports:
            - 8181:8181
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=plexpy.misury.tv
            - VIRTUAL_PORT=8181
        restart: always

#    nzbhydra:
#        image: linuxserver/hydra
#        container_name: nzbhydra
#        volumes:
#            - /home/plex/config/nzbhydra:/config
#            - /home/plex/Downloads:/downloads
#            - /etc/localtime:/etc/localtime:ro
#        ports:
#            - 5075:5075
#        env_file: uidgid.env
#        environment:
#            - VIRTUAL_HOST=nzbhydra.misury.tv
#            - VIRTUAL_PORT=5075
#        restart: always

    muximux:
        image: linuxserver/muximux
        container_name: muximux
        volumes:
            - /home/plex/config/muximux:/config
            - /etc/localtime:/etc/localtime:ro
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=muximux.misury.tv
        restart: always

    radarr:
        image: linuxserver/radarr
        container_name: radarr
        volumes:
            - /home/plex/config/radarr:/config
            - /home/plex/Movies:/movies
            - /home/plex/Downloads/complete:/downloads
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 7878:7878
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=radarr.misury.tv
            - VIRTUAL_PORT=7878
        restart: always

    ombi:
        image: linuxserver/ombi
        container_name: ombi
        volumes:
            - /home/plex/config/ombi:/config
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 3579:3579
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=ombi.misury.tv
            - VIRTUAL_PORT=3579
        restart: always

#    nzbget:
#        image: linuxserver/nzbget
#        container_name: nzbget
#        volumes:
#            - /home/plex/config/nzbget:/config
#            - /home/plex/Downloads/complete:/complete
#            - /home/plex/Downloads:/downloads
#        ports:
#            - 6789:6789
#        env_file: uidgid.env
#        environment:
#            - VIRTUAL_HOST=nzbget.misury.tv
#            - VIRTUAL_PORT=6789
#       restart: always
